#!/usr/bin/env bash

SCRIPT_PATH=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

cd "$SCRIPT_PATH"
echo "now working from directory: \"$(pwd -P)\""

#MKCMD="latexmk DVG001_lab2 -outdir=build -pdf -pdflatex=\"pdflatex -shell-escape -interaction=nonstopmode\""
latexmk DVG001_lab2 -outdir=build -pdf -pdflatex="pdflatex -interaction=nonstopmode -shell-escape"
latexmk DVG001_lab2 -outdir=build -pdf -pdflatex="pdflatex -interaction=nonstopmode -shell-escape"
latexmk DVG001_lab2 -outdir=build -pdf -pdflatex="pdflatex -interaction=nonstopmode -shell-escape"

#$MKCMD
#$MKCMD
#$MKCMD

